name: db_integration
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  build_runner: ^2.4.9
  envied: ^0.5.4+1
  mysql1: ^0.20.0
  # path: ^1.8.0

dev_dependencies:
  envied_generator: ^0.5.4+1
  lints: ^3.0.0
  test: ^1.24.0
