name: Iskomyut
description: An app where users can find the closest terminals, schedule, and book a seat on a bus/UV Express going to nearby provinces

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  flutter_map: ^6.1.0
  mysql1: ^0.20.0
  flutter_dotenv: ^5.1.0
  front_end:
     path: 'front_end'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true